book/urls.py
# from django.conf.urls import url
# from django.contrib import admin
# from . import views

# app_name = 'book'
# urlpatterns = [
#     path('catalog', viwes.index, name = 'index'),
#     path('catalog/books/', views.BookList, name="books"),
#     path('catalog/book/<int:id>/', views.BookDetail, name="book-detail"),


# ]

poll/urls.py
from django.urls import path ,include
from . import views


app_name  = 'poll'
urlpatterns = [
    path('', views.index.as_view(), name = 'index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/result/', views.result, name='result'),
    path('<int:question_id>/vots/', views.vote, name='vots'),
]

polls/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('poll/', include('poll.urls'))
   # path('book/', include('myapp.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

book/models.py
from django.db import models
from django.utils import timezone
import datetime
import uuid

class Writer(models.Model):
    name = models.CharField(max_length = 300)
    family = models.CharField(max_length = 300)
    Email = models.EmailField(blank = True)
    born = models.DateField(blank = True,null = True)
    def __str__(self):
        return '%s, %s' % (self.name, self.family)

    def get_absolute_url(self):
        return reverse("model_detail", args=[str(self.id)] )



class Book(models.Model):
    id = models.UUIDField(primary_key = True, default = uuid.uuid4, help_text = "unique id for each book")
    writer = models.ForeignKey('Writer', on_delete=models.CASCADE)
    name = models.CharField(max_length = 300)
    Create =  models.DateField(blank = True, null = True)
    def __str__(self):
        return '%s, %s' %(self.writer,self.name)

myapp/models.py
from django.db import models
from django.utils import timezone
import datetime
import uuid

class Author(models.Model):
    """
    Model representing an author.
    """
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    def get_absolute_url(self):
        """
        Returns the url to access a particular author instance.
        """
        return reverse('author-detail', args=[str(self.id)])


    def __str__(self):
        """
        String for representing the Model object.
        """
        return '%s, %s' % (self.last_name, self.first_name)



import uuid # Required for unique book instances

class BookInstance(models.Model):
    """
    Model representing a specific copy of a book (i.e. that can be borrowed from the library).
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this particular book across whole library")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Book availability')

    class Meta:
        ordering = ["due_back"]


    def __str__(self):
        """
        String for representing the Model object
        """
        return '%s (%s)' % (self.id,self.book.title)



from django.urls import reverse #Used to generate URLs by reversing the URL patterns

class Book(models.Model):
    """
    Model representing a book (but not a specific copy of a book).
    """
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file.
    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the book")
    isbn = models.CharField('ISBN',max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField('Genre', help_text="Select a genre for this book")
    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.title


    def get_absolute_url(self):
        """
        Returns the url to access a particular book instance.
        """
        return reverse('book-detail', args=[str(self.id)])


class Genre(models.Model):
    """
    Model representing a book genre (e.g. Science Fiction, Non Fiction).
    """
    name = models.CharField(max_length=200, help_text="Enter a book genre (e.g. Science Fiction, French Poetry etc.)")

    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.name

poll/models.py
from django.db import models
from django.utils import timezone
import datetime
import uuid

class Question(models.Model):
    text = models.CharField(max_length = 300)
    date = models.DateTimeField((""), auto_now=False, auto_now_add=False)
    def __str__(self):
       return '%s, %s' % (self.text, self.date)


class Choice(models.Model):
    question = models.ForeignKey(Question,on_delete = models.CASCADE)
    text = models.CharField(max_length =  300)
    vots = models.IntegerField(default=0)
    def __str__(self):
        return '%s, %s' % (self.vots, self.text)

book/views.py
from django.shortcuts import render

# Create your views here.

myapp/views.py
from django.shortcuts import render

# Create your views here.

poll/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.http import HttpResponse, HttpResponseRedirect
from  . import models
from django.views import generic


class index(generic.ListView):
    template_name = 'poll/index.html'
    context_object_name = 'objects'

    def get_queryset(self):
        return models.Question.objects.order_by('-date')[:5]





def detail(request, question_id):
    que = get_object_or_404(models.Question, id = question_id )

    context = {
    'que' : que
    }

    return render(request, 'poll/detail.html', context)
    #return HttpResponse("You're looking at question %s." % question_id)




def result(request, question_id):
    question = get_object_or_404(models.Question, id=question_id)

    return render(request, 'poll/result.html', {'question': question})





def vote(request, question_id):
    que = get_object_or_404(models.Question, id=question_id)
    context = {
    'que' : que,
    'error_message' : "choice is not avibail"
    }
    try:
        selected_choice = que.choice_set.get(id=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'poll/detail.html', context)
    else:
        selected_choice.vots += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('poll:result', args=(que.id,)))

book/templates/book/base.html
<!DOCTYPE html>
<html lang="en">

<head>

{% load static %}
<link rel = "stylesheet" href = "{% static 'book/style.css' %}">

    {% block title %}
        <title>
            Local library
        </title>
    {% endblock  %}
</head>

<body>
    {% block sdiebar %}
        <!-- this is block-->
    {% elock %}

    {% block content%}
    <!-- this is a commet-->

    {% endblock  %}
</body>
</html>

book/templates/book/index.html
{% extends 'base.html' %}

 {% block  content%}
        <h1>WOOOOOOOOOOOOOOOOw Your Are A programmer {{ name }}</h1>
    {% endblock %}

poll/templates/poll/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Vote</title>

  </head>
  <style>
  body  {
    background : black;
  }
    </style>
  <body>

  {% block base %}

  {% endblock  %}


  </body>
</html>

poll/templates/poll/detail.html
<h1 style="color: red;"> {{ que.text }} </h1>

{% if error_massage  %}<p> <strong> {{ error_massage }} </strong> </p>{% endif %}

<form action = "{% url 'poll:vots' que.id %}" method = "POST">
{% csrf_token %}

{% for choice in que.choice_set.all %}
	<input type="radio" name = "choice" id = "choice{{ forloop.counter }}" value = "{{ choice.id }}" />
	<label for = "choice{{ forloop.counter }}">{{ choice.text }}</label><br />
{% endfor %}
<input type = "submit"  value = "vote" />


</form>

poll/templates/poll/index.html
{% if objects %}
    <ul>
    {% for question in objects %}
    	<li><a href="{% url 'poll:detail' question.id %}"> {{ question.text }} </a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

poll/templates/poll/result.html
<h1>{{ question.text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.text }} -- {{ choice.vots }} vote{{ choice.vots|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'poll:detail' question.id %}">Vote again?</a><hr>
<a href="{% url 'poll:index'  %}"> back to home </a>